project:
  type: website
  output-dir: docs
  
website:
  title: "Welcome To My Portfolio!"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - work_experience.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/omid-khan
        target: _blank
      - icon: github
        href: https://github.com/omidk414
        target: _blank
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Omid Khan"
    

format:
  html:
    theme: cerulean
    toc: true

editor: source

