---
title: "About Me"
about:
  id: me
  template: broadside
---

:::{#me}

## Goals

As a passionate software engineer, my goals include:

- Leveraging technology to drive actionable insights from data.
- Building innovative and efficient solutions to real-world problems.
- Collaborating with like-minded professionals to achieve excellence.

## Education

I hold a Bachelor of Science in Computer Science from California State University, East Bay, where I excelled in courses like:

- Software Engineering
- Data Structures & Algorithms
- Operating Systems
- Computer Architecture
- Object-Oriented Programming

This robust education has equipped me with a versatile skill set, enabling me to tackle complex software engineering challenges with confidence.

:::

<p>Thanks for checking out my portfolio!</p>

<p>Hover over this text: 
<span class="hover-letter" data-hover="Passionate">P</span>
<span class="hover-letter" data-hover="Innovative">I</span>
<span class="hover-letter" data-hover="Collaborative">C</span>
</p>
